{{- if .Values.django.ingress.enabled -}}
{{- $fullName := include "defectdojo.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    defectdojo.org/component: django
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "defectdojo.chart" . }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if or .Values.django.ingress.annotations .Values.gke.useGKEIngress }}
  annotations:
    {{- with .Values.django.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.gke.useGKEIngress }}
    kubernetes.io/ingress.class: gce
    {{- if .Values.gke.useManagedCertificate }}
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: {{ $fullName }}-django
    {{- end }}
    {{- end }}
{{- end }}
spec:
  {{- if .Values.django.ingress.ingressClassName }}
  ingressClassName: {{ .Values.django.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.django.ingress.activateTLS }}
  tls:
    - hosts:
        - {{ .Values.host | quote }}
      {{- if .Values.django.ingress.secretName }}
      secretName: {{ .Values.django.ingress.secretName | quote }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.host | quote }}
      http:
        paths:
          - path: {{ .Values.django.ingress.path | default "/" | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-django
                port:
                  name: http
{{- end }}
